### ISSUE TITLE
Dimensions broken after 1.19.10

### ISSUE THREAD

**Issue by UnknownOre** [jasonwynn10/NativeDimensions#7]
### Issue description

- Expected result: get teleported properly
- Actual result: get stuck in loading screen

### Steps to reproduce the issue
1. Enter a portal

### OS and versions

* Plugin Version: 1.0.0-beta7
* PocketMine-MP:4.6.0
* PHP:php8

**Comment by JoshuaPHYT** [comment]
when new update

**Comment by JavierLeon9966** [comment]
2 hours ago
